language: node_js
node_js:
- "stable"
before_deploy: "echo 'ready?'"
deploy:
  provider: npm
  email: "luigisenzamici@gmail.com"
  api_key: $NPM_TOKEN
  skip_cleanup: true
notifications:
  email:
    recipients:
    - luigisenzamici@gmail.com
    on_success: change
    on_failure: always
